# 使用 Docker 一件部署你的 数据库
services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
  mysql:
    image: mysql
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: houcloud
    command:
      --default-authentication-plugin=caching_sha2_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    restart: always
networks:
  default:
    external: true
    name: houcloud


